# ファイル名: クラス名 のように記載する。

common:
  # ドラ表、山残り枚数などすべてのプレーヤーについて共通の特徴量
  doraV0.py: DoraV0
  

on_reach_dahai: 
  # 持ち点、手牌、副露牌などプレーヤーごとに異なる特徴量
  # すべてのアクションについて抽出する特徴量
  ankanV0.py: AnkanV0
  anpaiV0.py: AnpaiV0
  dfsV0.py: DfsV0

on_pon_chi_kan: 
  # ポン、チー、カンのときのみ抽出する特徴量
  pon_chi_kan_dfsV0.py: PonChiKanDfsV0

